/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c9f03b65-253e-4078-a37d-0740aeacebc6",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_3YIIIMZ7w",
    "aws_user_pools_web_client_id": "57fudtee8fmd4k7qjhhsorp4be",
    "oauth": {}
};


export default awsmobile;
